#!/bin/sh
#
#

# coco for sunjiajia
#
# chkconfig:   2345 30 80
# description: coco start script

# Provides:          coco
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:  I Love Sunjiajia.



case "$1" in
start)
    # Starting Coco...
    source /opt/py3/bin/activate 
    cd /opt/coco && ./cocod start -d 
    sleep 1     
    ;;

stop)
    # Stopping Coco...
    pid=`ps -ef | grep -v grep | egrep '(cocod)' | awk '{print $2}'`
    kill -9 ${pid}
    
    sleep 1
    ;;

restart)
    

    # Restarting Cocod"   
    pid=`ps -ef | grep -v grep | egrep '(cocod)' | awk '{print $2}'`
    kill -9 ${pid}
    

    source /opt/py3/bin/activate
    cd /opt/coco && ./cocod restart -d 
    sleep 1

    ;;

*)
    echo "Usage:  {start|stop|restart}"
    ;;
esac
exit 0
