#!/bin/sh
#
#

# jms for sunjiajia
#
# chkconfig:   2345 20 80
# description: jms start script

# Provides:          jms
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 5
# Description:  I Love Sunjiajia.


case "$1" in
start)
    # Starting Jms...
    source /opt/py3/bin/activate
    cd /opt/jumpserver && ./jms start all -d 
    sleep 1     
    ;;

stop)
    # Stopping Jms...
    pid=`ps -ef | grep -v grep | egrep '(gunicorn|celery|beat)' | awk '{print $2}'`
    kill -9 ${pid}
    ;;

restart)
    # Restarting Jms...
    pid=`ps -ef | grep -v grep | egrep '(gunicorn|celery|beat)' | awk '{print $2}'`
    kill -9 ${pid}

    sleep 1
    echo "Starting Jms..."   
    source /opt/py3/bin/activate
    cd /opt/jumpserver && ./jms start all -d 
    sleep 1
    ;;

*)
    echo "Usage:  {start|stop|restart}"
    ;;
esac
exit 0
